#include "mainwindow.h"

#include <QApplication>

//Main is left unntouched and is generated by the program

int main(int argc, char *argv[])
{


    QApplication a(argc, argv);
/*
    //set style sheet
    QFile qss("Diplaytap.qss");
    qss.open(QFile::ReadOnly);
    QString style = QLatin1String(qss.readAll());
    a.setStyleSheet(style);
*/
    MainWindow w;
    w.setWindowState(Qt::WindowFullScreen); //George: Changed it to full screen
    //w.setFixedSize(1600,900); //original
    w.show();
    return a.exec();
}
